### ISSUE TITLE
runtime.rb:74:in `require': cannot load such file -- refinerycms/membe rs (LoadError)

### ISSUE THREAD

**Issue by udokrass** [rbriank/refinerycms_membership#30]
Hi all,

When I follow the readme I get following error:
"runtime.rb:74:in `require': cannot load such file -- refinerycms/members (LoadError)"

Is there a planned update of this engine?
Because the last commit is about 1 year ago.
That would be great!
Or is there another member engine for refinery?

Thanks and regards,
Udo

**Comment by rbriank** [comment]
It's really out of date. I don't know of any others.
B

**Comment by tsemana** [comment]
Hi, here's a fork that seems to have been updated to work with Refinery 2.0.0
https://github.com/mark-secondbureau/refinerycms_membership/tree/2buro-2.1

**Comment by rbriank** [comment]
Cool.  Thanks!

B

On Mon, Jun 18, 2012 at 11:19 AM, tsemana <
reply@reply.github.com

**Comment by Jesterovskiy** [comment]
This fork no longer exists. Do you have some solutions for this problem?

**Comment by rbriank** [comment]
No. I haven't worked on this, or with refinery for some time now.
